apiVersion: v1
kind: Service
metadata:
  name: {{ include "tokeisrv.fullname" . }}
  labels:
    {{- include "tokeisrv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "tokeisrv.name" . }}
